export const SWIPE_CONFIG = {
  THRESHOLD_VELOCITY: 0.3,
  THRESHOLD_DISTANCE: 0.35,
  MAX_ROTATION: 15,
  NEXT_SCALE_MIN: 0.92,
  NEXT_SCALE_MAX: 1,
  AUTO_SWIPE_DELAY: 2000,
  ANIMATION_DURATION: 800,
  SWIPE_END_POSITION_MULTIPLIER: 1.5,
};

export const easeOutQuint = (x) => 1 - Math.pow(1 - x, 5);